spring.application.name=agora-gateway

# Gateway port
server.port=8080

# Upstream services
services.auth.base-url=http://localhost:8083
services.user.base-url=http://localhost:8081

# Paths that bypass JWT validation in the global filter
# /api/internal/auth/** is intended for service-to-service calls using service tokens
gateway.auth.public-paths=/api/auth/authenticate,/api/auth/health,/actuator/health,/api/internal/auth/

# Expose auth endpoints as /api/auth/** and forward to Auth /public/auth/**
spring.cloud.gateway.server.webflux.routes[0].id=auth-public-and-token-endpoints
# URL base del servicio de autenticacion
spring.cloud.gateway.server.webflux.routes[0].uri=${services.auth.base-url}
# Ruta por la cual debe de llegar el request
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
# Redirecciona la ruta del request, y la renombra en base a lo que capturo en la primera url
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api/auth/(?<segment>.*),/public/auth/$\\{segment}

# Example protected route to user-service
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=${services.user.base-url}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/api/users/(?<segment>.*),/$\\{segment}

# Expose Auth internal endpoints as /api/internal/auth/** and forward to /internal/**
spring.cloud.gateway.server.webflux.routes[2].id=auth-internal
spring.cloud.gateway.server.webflux.routes[2].uri=${services.auth.base-url}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/internal/auth/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/api/internal/auth/(?<segment>.*),/internal/$\\{segment}
