//! Port for session repository access.
//!
//! Abstracts session creation, lookup, revocation, and cleanup for authentication use cases.
//!
//! Adapters must implement this trait to provide persistence or external session management.

use futures::future::BoxFuture;
use crate::core::identity::UserIdentity;

/// Opaque session type for use case contracts (to be defined in usecases).
pub struct Session {/* fields omitted for now */}

/// Contract for session repository access.
pub trait SessionRepository: Send + Sync {
	/// Create a new session for a user.
	/// 
	/// # Arguments
	/// * `session_id` - The session ID to store (generated by IssueSession)
	/// * `user` - The user identity
	/// * `refresh_token_hash` - Hash of the refresh token
	/// * `metadata` - Session metadata JSON
	fn create_session(&self, session_id: &str, user: &UserIdentity, refresh_token_hash: &str, metadata: &str) -> BoxFuture<'_, ()>;
	
	/// Find a session by refresh token hash.
	fn find_by_refresh_token_hash(&self, hash: &str) -> BoxFuture<'_, Option<Session>>;

	/// Find a session by session ID.
	/// 
	/// Returns the session only if it is not revoked and not expired.
	fn find_by_id(&self, session_id: &str) -> BoxFuture<'_, Option<Session>>;

	/// Revoke a session by id or token hash.
	fn revoke_session(&self, session_id: &str) -> BoxFuture<'_, ()>;

	/// Revoke all sessions for a user.
	fn revoke_all_for_user(&self, user_id: &str) -> BoxFuture<'_, ()>;

	/// Delete all expired sessions.
	fn delete_expired(&self) -> BoxFuture<'_, ()>;
}

